FROM alpine:latest

LABEL maintainer="arnulf.heimsbakk@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

RUN apk add --no-cache \
        bash \
        docker-cli \
        docker-compose \
        dumb-init;

COPY crontab /etc/crontabs/root
COPY docker-*.yml /root/

VOLUME /var/backups

CMD dumb-init -- crond -f -d 8
